name: Build rhtmlPalmTrees

on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: Build rhtmlPalmTrees
    permissions:
      checks: write
      contents: read
    uses: Displayr/nixr-public/.github/workflows/build-flake-installable.yaml@master
    with:
      installable-path: pkgs.x86_64-linux.rPackages.rhtmlPalmTrees
      build-args: --override-input rhtmlPalmTrees .
      installable-name: rhtmlPalmTrees
    secrets: inherit
